// flow-typed signature: 3a520f6c43f5def0b49226eff23c46c2
// flow-typed version: <<STUB>>/dedent-js_v1.0.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dedent-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dedent-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dedent-js/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dedent-js/lib/index.js' {
  declare module.exports: $Exports<'dedent-js/lib/index'>;
}
