// flow-typed signature: 670e5f4b4855be6b073e1dd9a4f76dca
// flow-typed version: <<STUB>>/intl-messageformat-parser_v1.6.3/flow_v0.99.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'intl-messageformat-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'intl-messageformat-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'intl-messageformat-parser/build' {
  declare module.exports: any;
}

declare module 'intl-messageformat-parser/dist/parser' {
  declare module.exports: any;
}

declare module 'intl-messageformat-parser/lib/parser' {
  declare module.exports: any;
}

declare module 'intl-messageformat-parser/src/parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'intl-messageformat-parser/build.js' {
  declare module.exports: $Exports<'intl-messageformat-parser/build'>;
}
declare module 'intl-messageformat-parser/dist/parser.js' {
  declare module.exports: $Exports<'intl-messageformat-parser/dist/parser'>;
}
declare module 'intl-messageformat-parser/index' {
  declare module.exports: $Exports<'intl-messageformat-parser'>;
}
declare module 'intl-messageformat-parser/index.js' {
  declare module.exports: $Exports<'intl-messageformat-parser'>;
}
declare module 'intl-messageformat-parser/lib/parser.js' {
  declare module.exports: $Exports<'intl-messageformat-parser/lib/parser'>;
}
declare module 'intl-messageformat-parser/src/parser.js' {
  declare module.exports: $Exports<'intl-messageformat-parser/src/parser'>;
}
