// flow-typed signature: c640b88154e0d7470af3106696f20988
// flow-typed version: <<STUB>>/jasmine-object-matchers-jest_v0.1.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jasmine-object-matchers-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jasmine-object-matchers-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jasmine-object-matchers-jest/lib/matchers-1.3' {
  declare module.exports: any;
}

declare module 'jasmine-object-matchers-jest/lib/matchers-2.0' {
  declare module.exports: any;
}

declare module 'jasmine-object-matchers-jest/lib/objectMatchers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jasmine-object-matchers-jest/index' {
  declare module.exports: $Exports<'jasmine-object-matchers-jest'>;
}
declare module 'jasmine-object-matchers-jest/index.js' {
  declare module.exports: $Exports<'jasmine-object-matchers-jest'>;
}
declare module 'jasmine-object-matchers-jest/lib/matchers-1.3.js' {
  declare module.exports: $Exports<'jasmine-object-matchers-jest/lib/matchers-1.3'>;
}
declare module 'jasmine-object-matchers-jest/lib/matchers-2.0.js' {
  declare module.exports: $Exports<'jasmine-object-matchers-jest/lib/matchers-2.0'>;
}
declare module 'jasmine-object-matchers-jest/lib/objectMatchers.js' {
  declare module.exports: $Exports<'jasmine-object-matchers-jest/lib/objectMatchers'>;
}
