// flow-typed signature: 51f6b233aa36b76a20a0f23c5ab5d4b7
// flow-typed version: <<STUB>>/redent_v3.0.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'redent/index' {
  declare module.exports: $Exports<'redent'>;
}
declare module 'redent/index.js' {
  declare module.exports: $Exports<'redent'>;
}
